#!/bin/bash

TITLE="Apache Spark Switch Script\n-------------------\nhttps://github.com/heuermh/brew-apache-spark-switcher"
DISCLAMER="\nDISCLAMER: This script assumes you've installed apache-spark versions using\nbrew install apache-spark/apache-spark15/apache-spark141"
HELP="Usage: spswitch [VERSION]\n\nVERSION - Supports versions 1.6.*, 1.5.*, and 1.4.1\n\nInstalled Versions:\n"
SWITCHING="Switchd to: "
NOT_FOUND="Version %s not found.\n"
VERSION=$1

function list_versions () {
  list_16x
  list_15x  
  list_141
}

function list_ver {
  local main_apache_spark_version="$1"
  local compare="$2"
  IFS='.' read -a array <<< "$main_apache_spark_version"
  if [ "${array[1]}" = "$compare" ]; then
    printf "${array[0]}.${array[1]}.${array[2]} - Type 'spswitch 1.$compare' to switch to this version.\n"
  fi
}

function list_16x () {
  local ls_res=`ls /usr/local/Cellar/apache-spark/ 2>/dev/null`
  list_ver "${ls_res#\n}" "6"
}

function list_15x () {
  local ls_res=`ls /usr/local/Cellar/apache-spark15/ 2>/dev/null`
  list_ver "${ls_res#\n}" "5"
}

function list_141 () {
  local ls_res=`ls /usr/local/Cellar/apache-spark141/ 2>/dev/null`
  list_ver "${ls_res#\n}" "4"
}

function switch_to {
  local base_path="$1"
  # see brew unlink/link below  
  printf "$SWITCHING $base_path\n"
  printf "Use SPARK_HOME=$base_path/libexec\n"
}

function switchto_x {
  local clean="$1" 
  if [ "$clean" != "" ]; then
    switch_to "/usr/local/Cellar/$2/$clean"
  else
    printf "$NOT_FOUND\n" "$3"
  fi
}

function switchto_16x {
  local ls_res=`ls /usr/local/Cellar/apache-spark/ 2>/dev/null`
  brew unlink apache-spark15 > /dev/null 2>&1
  brew unlink apache-spark141 > /dev/null 2>&1
  brew link apache-spark > /dev/null 2>&1
  switchto_x "${ls_res#\n}" "apache-spark" "1.6.x"
}

function switchto_15x {
  local ls_res=`ls /usr/local/Cellar/apache-spark15/ 2>/dev/null`
  brew unlink apache-spark > /dev/null 2>&1
  brew unlink apache-spark141 > /dev/null 2>&1
  brew link apache-spark15 > /dev/null 2>&1
  switchto_x "${ls_res#\n}" "apache-spark15" "1.5.x"
}

function switchto_141 {
  local ls_res=`ls /usr/local/Cellar/apache-spark141/ 2>/dev/null`
  brew unlink apache-spark > /dev/null 2>&1
  brew unlink apache-spark15 > /dev/null 2>&1
  brew link apache-spark141 > /dev/null 2>&1
  switchto_x "${ls_res#\n}" "apache-spark141" "1.4.1"
}

# EXECUTING STARTS HERE:

# Help / List 
if [ "$VERSION" = "" ]; then
    printf "\n$TITLE\n"
    printf "\n$HELP\n"
    list_versions
    printf "$DISCLAMER\n"
else # Switch
  if [ "$VERSION" = "1.6" ]; then
    switchto_16x
  elif [ "$VERSION" = "1.5" ]; then
    switchto_15x
  elif [ "$VERSION" = "1.4" ]; then
    switchto_141
  else
    echo "Unknown version."
  fi
fi
